### PR TITLE
Create Week1

### PR DESCRIPTION
**Pull request by Yuy1L1**

### CODE REVIEW

**Comment by Yuy1L1** [comment]
Link of the first week's discussion slides

**Comment by matloff** [comment]
Thanks very much, Yuyi, good to put this material on the repo.

Please note that you will need to run the server for Quiz 0, starting it
again each day because CSIF reboots at midnight.

Norm

**Comment by Yuy1L1** [comment]
> Thanks very much, Yuyi, good to put this material on the repo. Please note that you will need to run the server for Quiz 0, starting it again each day because CSIF reboots at midnight. Norm

Noted! I will rerun the server due to the reboot. Is the material on the repo now?

**Comment by matloff** [comment]
On Thu, Apr 06, 2023 at 08:54:45PM -0700, Yuyi Li wrote:
 
>    Is the material on the repo now?

Hmm, I don't see it.

Norm

**Comment by Yuy1L1** [comment]
I think I need to have "write access" to merge pull requests.

**Comment by matloff** [comment]
I forgot, you only have access to the *recss23 repo.  Added now.

Norm

**Comment by alejandroarmas** [comment]
Hi @Yuy1L1,

Is it possible for the code snippets you showed in class to be linked as well, or were those taken from [here](https://github.com/matloff/fasteR)? Thanks!

**Pull request merged**
